galaxy_info:
  author: TJ Zimmerman
  description: Download a CentOS 7 iso and create a bootable USB drive from it.
  license: GPL-3.0-only
  min_ansible_version: 2.9
  platforms:
  - name: CentOS
    versions:
    - 7.7
